"""empty message

Revision ID: 168516ab8234
Revises: 
Create Date: 2018-07-10 16:05:31.869799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168516ab8234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('apikey', sa.String(length=256), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikeys_apikey'), 'apikeys', ['apikey'], unique=True)
    op.create_index(op.f('ix_apikeys_username'), 'apikeys', ['username'], unique=True)
    op.create_table('bootstrap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('apikey', sa.String(length=256), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bootstrap_apikey'), 'bootstrap', ['apikey'], unique=True)
    op.create_index(op.f('ix_bootstrap_username'), 'bootstrap', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bootstrap_username'), table_name='bootstrap')
    op.drop_index(op.f('ix_bootstrap_apikey'), table_name='bootstrap')
    op.drop_table('bootstrap')
    op.drop_index(op.f('ix_apikeys_username'), table_name='apikeys')
    op.drop_index(op.f('ix_apikeys_apikey'), table_name='apikeys')
    op.drop_table('apikeys')
    # ### end Alembic commands ###
