"""empty message

Revision ID: fd5ba26fedee
Revises: 
Create Date: 2018-07-11 12:47:33.110428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5ba26fedee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('apikey', sa.String(length=256), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('methods', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikeys_apikey'), 'apikeys', ['apikey'], unique=True)
    op.create_index(op.f('ix_apikeys_methods'), 'apikeys', ['methods'], unique=False)
    op.create_index(op.f('ix_apikeys_username'), 'apikeys', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikeys_username'), table_name='apikeys')
    op.drop_index(op.f('ix_apikeys_methods'), table_name='apikeys')
    op.drop_index(op.f('ix_apikeys_apikey'), table_name='apikeys')
    op.drop_table('apikeys')
    # ### end Alembic commands ###
